routes/web.php
<?php

use App\Http\Controllers\ExploreController;
use App\Http\Controllers\FollowsController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\NotificationsController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostLikesController;
use App\Http\Controllers\ProfilesController;
use App\Http\Controllers\ReplyController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

# Main page
route::get('/', MainController::class)->name('main');

# Posts
Route::resource('posts', PostController::class);

# Replies
Route::get('/posts/{post}/replies', [ReplyController::class, 'create'])->name('replies.create');
Route::post('/posts/{post}/replies', [ReplyController::class, 'store'])->name('replies.store');

# PostLikes
Route::post('/posts/{post}/like', [PostLikesController::class, 'storeLike']);
Route::post('/posts/{post}/dislike', [PostLikesController::class, 'storeDislike']);
Route::delete('/posts/{post}/like', [PostLikesController::class, 'destroy']);
Route::delete('/posts/{post}/dislike',[PostLikesController::class, 'destroy']);


# Profile
Route::get('/profiles/{user:username}', [ProfilesController::class, 'show'])->name('profiles.show');
Route::get('/profiles/{user:username}/edit', [ProfilesController::class, 'edit']);
Route::patch('/profiles/{user:username}', [ProfilesController::class, 'update']);
Route::get('/profiles/{user:username}/destroy', [ProfilesController::class, 'showDestroy'])->name('profiles.showdestroy');
Route::delete('/profiles/{user:username}/destroy', [ProfilesController::class, 'destroy'])->name('profiles.destroy');


# Follow store
Route::post('/profiles/{user:username}/follow', FollowsController::class);

# Explore
route::get('/explore', ExploreController::class)->name('explore');

# Notifications
route::get('/notifications', NotificationsController::class)->name('notifications');

resources/views/qchan/_create.blade.php
<div class="border border-blue-400 rounded-lg px-8 py-6 mb-8">
    <form method="POST" action="{{ route('posts.index')}}">
        @csrf
        <textarea
            name="body"
            class="w-full"
            placeholder="What's on your mind?"
        ></textarea>

        <hr class="my-4">

        <footer class="flex justify-between">
            <img
                src=" {{ auth()->user()->avatar }}"
                alt="Your Avatar"
                class="rounded-full mr-2"
                height="50"
                width="50"
            >
            <button type="submit" class="bg-blue-500 rounded-lg shadow py-2 px-2 text-white"
            >
                Post
            </button>

        </footer>

    </form>

    @error('body')
    <p class="text-red-500 text-sm mt-2">{{ $message }}</p>
    @enderror
</div>

resources/views/qchan/_edit.blade.php
<x-app>
    <div class="border border-blue-400 rounded-lg px-8 py-6 mb-8">
        <form method="POST" action="{{ route('posts.update', $post->id)}}">
            @csrf
            @method('PUT')
            <textarea
                name="body"
                class="w-full"
            >{{$post->body}}</textarea>

            <hr class="my-4">

            <footer class="flex justify-between">
                <img
                    src=" {{ current_user()->avatar }}"
                    alt="Your Avatar"
                    class="rounded-full mr-2"
                    height="50"
                    width="50"
                >
                <button type="submit" class="bg-blue-500 rounded-lg shadow py-2 px-2 text-white"
                >
                    Edit post
                </button>

            </footer>

        </form>

        @error('body')
        <p class="text-red-500 text-sm mt-2">{{ $message }}</p>
        @enderror
    </div>
</x-app>

resources/views/qchan/_explore.blade.php
<x-App>
        <div class="flex flex-column relative">
            <div class="flex-wrap mb-4 relative">
                <div class="font-weight-bold text-2xl mt-2 mb-6 border-bottom">Here you can explore new users!</div>
            @foreach($users as $user)
                        @if(!current_user()->following($user) && !current_user()->is($user))

                                <a href="{{ $user->path() }}" class="p-4">
                                    <img src="{{ $user->avatar }}"
                                         alt="{{ $user->username }}'s avatar"
                                         width="60px"
                                         class="mr-4 rounded absolute" />
                                    <span class="font-bold d-xl-block text-center mb-4">{{'@'.$user->username}}</span>
                                </a>
                            @endif
                    @endforeach
                @if($onlyUser)
                    <div class="text-lg font-bold text-red-500 mt-12">No other users exists at the moment, invite your friends!</div>
                    @endif

            </div>
            {{$users->links()}}
        </div>
</x-App>

resources/views/qchan/_followers-list.blade.php
<div class="bg-gray-200 rounded-lg py-4 px-6">
    <h3 class="font-bold text-xl mb-4">I'm following:</h3>

    <ul>
        @forelse(current_user()->follows as $user)
            <li class="mb-4 list-none">
                <div>
                    <a class="flex items-center text-sm" href="{{ route('profiles.show', $user->username)}}">
                        <img
                            src="{{ $user->avatar }}"
                            alt=""
                            class="rounded-full mr-2"
                            width="40"
                        >

                        {{ $user->name }}
                    </a>

                </div>
            </li>
        @empty
            <li class="alert-warning">Not following anyone</li>
        @endforelse
    </ul>
    <h3 class="font-bold text-xl mb-4">My followers:</h3>
    @forelse(current_user()->followers()->get() as $user)
        <li class="mb-4 list-none">
            <div>
                <a class="flex items-center text-sm" href="{{ route('profiles.show', $user->username)}}">
                    <img
                        src="{{ $user->avatar }}"
                        alt=""
                        class="rounded-full mr-2"
                        width="40"
                    >

                    {{ $user->name }}
                </a>

            </div>
        </li>
    @empty
        <li>No Followers yet</li>
    @endforelse
</div>

resources/views/qchan/_index.blade.php
<x-app>
    <div class="lg:flex-1 lg:mx-10 mb-2" style="max-width:700px">
        @include('qchan._create')
        @include('qchan._timeline')
    </div>
</x-app>

resources/views/qchan/_links.blade.php
<ul class="aninavtree ml-24">
    <li class="links {{ Request::path() === 'posts' ? 'links-active' : ''}}">
        <a href="{{ route('posts.index') }}">
            Home
        </a>
    </li>

    <li class="links {{ Request::path() === 'explore' ? 'links-active' : ''}}">
        <a href="{{ route('explore') }}">
            Explore
        </a>
    </li>

    <li class="links {{ Request::path() === 'notifications' ? 'links-active' : ''}}">
        <a href="{{ route('notifications') }}">
            Notifications
        </a>
    </li>

    <li class="links {{ Route::getFacadeRoot()->current()->uri() === 'profiles/{user}' ? 'links-active' : ''}}">
        <a href="{{ route('profiles.show', current_user()) }}">
            Profile
        </a>
    </li>
</ul>

<nav class="aninav">
    <ul class="aninav__list">

        <li class="aninav__listitem {{ Request::path() === 'posts' ? 'aninav__listitem-active' : ''}}">
            <a href="{{ route('posts.index') }}">
                <svg class="svg-icon" viewBox="0 0 20 20" width="100" title="home">
                    <path d="M18.121,9.88l-7.832-7.836c-0.155-0.158-0.428-0.155-0.584,0L1.842,9.913c-0.262,0.263-0.073,0.705,0.292,0.705h2.069v7.042c0,0.227,0.187,0.414,0.414,0.414h3.725c0.228,0,0.414-0.188,0.414-0.414v-3.313h2.483v3.313c0,0.227,0.187,0.414,0.413,0.414h3.726c0.229,0,0.414-0.188,0.414-0.414v-7.042h2.068h0.004C18.331,10.617,18.389,10.146,18.121,9.88 M14.963,17.245h-2.896v-3.313c0-0.229-0.186-0.415-0.414-0.415H8.342c-0.228,0-0.414,0.187-0.414,0.415v3.313H5.032v-6.628h9.931V17.245z M3.133,9.79l6.864-6.868l6.867,6.868H3.133z"></path>
                </svg>
            </a>
        </li>

        <li class="aninav__listitem {{ Request::path() === 'explore' ? 'aninav__listitem-active' : ''}}">
            <a href="{{ route('explore')}}">
                <svg class="svg-icon" viewBox="0 0 20 20" width="100" title="explore">
                    <path d="M18.125,15.804l-4.038-4.037c0.675-1.079,1.012-2.308,1.01-3.534C15.089,4.62,12.199,1.75,8.584,1.75C4.815,1.75,1.982,4.726,2,8.286c0.021,3.577,2.908,6.549,6.578,6.549c1.241,0,2.417-0.347,3.44-0.985l4.032,4.026c0.167,0.166,0.43,0.166,0.596,0l1.479-1.478C18.292,16.234,18.292,15.968,18.125,15.804 M8.578,13.99c-3.198,0-5.716-2.593-5.733-5.71c-0.017-3.084,2.438-5.686,5.74-5.686c3.197,0,5.625,2.493,5.64,5.624C14.242,11.548,11.621,13.99,8.578,13.99 M16.349,16.981l-3.637-3.635c0.131-0.11,0.721-0.695,0.876-0.884l3.642,3.639L16.349,16.981z"></path>
                </svg>
            </a>
        </li>

        <li class="aninav__listitem {{ Request::path() === 'notifications' ? 'aninav__listitem-active' : ''}}">
            <a href="{{ route('notifications')}}">
                <svg class="svg-icon" viewBox="0 0 20 20" width="100" title="notifications">
                    <path d="M14.38,3.467l0.232-0.633c0.086-0.226-0.031-0.477-0.264-0.559c-0.229-0.081-0.48,0.033-0.562,0.262l-0.234,0.631C10.695,2.38,7.648,3.89,6.616,6.689l-1.447,3.93l-2.664,1.227c-0.354,0.166-0.337,0.672,0.035,0.805l4.811,1.729c-0.19,1.119,0.445,2.25,1.561,2.65c1.119,0.402,2.341-0.059,2.923-1.039l4.811,1.73c0,0.002,0.002,0.002,0.002,0.002c0.23,0.082,0.484-0.033,0.568-0.262c0.049-0.129,0.029-0.266-0.041-0.377l-1.219-2.586l1.447-3.932C18.435,7.768,17.085,4.676,14.38,3.467 M9.215,16.211c-0.658-0.234-1.054-0.869-1.014-1.523l2.784,0.998C10.588,16.215,9.871,16.447,9.215,16.211 M16.573,10.27l-1.51,4.1c-0.041,0.107-0.037,0.227,0.012,0.33l0.871,1.844l-4.184-1.506l-3.734-1.342l-4.185-1.504l1.864-0.857c0.104-0.049,0.188-0.139,0.229-0.248l1.51-4.098c0.916-2.487,3.708-3.773,6.222-2.868C16.187,5.024,17.489,7.783,16.573,10.27"></path>
                </svg>
            </a>
        </li>

        <li class="aninav__listitem {{ Route::getFacadeRoot()->current()->uri() === 'profiles/{user}' ? 'aninav__listitem-active' : ''}}">
                <a href="{{ route('profiles.show', current_user()) }}">
                    <svg class="svg-icon" viewBox="0 0 20 20" width="100" title="profile">
                        <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
                    </svg>
                </a>
            </li>
    </ul>
</nav>


<section class="px-8 py-4 mb-2">
    <header class="container mx-auto">
        <h1>
            <img src="{{ asset('logo.png')}}" alt="Q chan logo">
        </h1>
    </header>
</section>

resources/views/qchan/_posts.blade.php
<div class="flex p-4 {{ $loop->last ? '' : 'border-b border-b-gray-400' }}">
    <div class="mr-2 flex-shrink-0">
        <a href="{{ route('profiles.show', $post->user) }}">
            <img
                src="{{ $post->user->avatar }}"
                alt=""
                class="rounded-full mr-2"
                width="40"
                height="40"
            >
        </a>
    </div>
    <div>
        <a href="{{ route('posts.show', $post->id) }}">
            <p class="font-bold mb-2">{{ $post->user->name }} •
                @if( $post->created_at != $post->updated_at) <u>Post edited</u> {{ $post->updated_at->diffForHumans()}}
                @else
                {{ $post->created_at->diffForHumans()}}
                @endif
        </a>

        <p class="text-sm mb-3">{{ $post->body }}</p>




    <div class="flex">
            <form method="POST" action="/posts/{{$post->id}}/like">
                @csrf
                @if($post->isLikedBy(current_user()))
                    @method('delete')
                @endif

                <div class="flex items-center mr-4">
                    <button type="submit">
                        <svg viewBox="0 0 20 20" class="{{ $post->isLikedBy(current_user()) ? 'text-blue-500' : 'text-gray-500' }} mr-1 w-6">
                            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <g class="fill-current">
                                    <polygon id="Combined-Shape" points="7 10 7 18 13 18 13 10 18 10 10 2 2 10 7 10"></polygon>
                                </g>
                            </g>
                        </svg>
                    </button>
                    {{ $post->likes ?: 0 }}
                </div>
            </form>

            <form method="POST" action="/posts/{{$post->id}}/dislike">
                @csrf
                @if($post->isDislikedBy(current_user()))
                    @method('delete')
                @endif

                <div class="flex items-center mr-4">
                    <button type="submit">
                        <svg viewBox="0 0 20 20" class="{{ $post->isDislikedBy(current_user()) ? 'text-blue-500' : 'text-grey-500' }} mr-1 w-6">
                            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <g class="fill-current">
                                    <path d="M13,10 L13,2 L7,2 L7,10 L2,10 L10,18 L18,10 L13,10 Z" id="Combined-Shape"></path>
                                </g>
                            </g>
                        </svg>
                    </button>
                    {{ - $post->dislikes ?: 0 }}
                </div>
            </form>
        @if( current_user()->is($post->user))
            <div>
                <form action="{{ route('posts.destroy', $post->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <a class="mr-4 ml-4 btn btn-primary" href="{{ ('/posts/' . $post->id . '/edit') }}">Edit</a>
                    <button class="mr-4 ml-4 btn btn-primary" type="submit">Delete</button>
                </form>
            </div>
        @endif
        <a class="btn btn-primary" href="{{route('replies.create', $post->id)}}">
            <svg viewBox="0 0 20 20" class="w-4">
                <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g class="fill-current">
                        <path d="M15,17 L15,14.009763 C15,11.795232 13.2081782,10 10.9976305,10 L8,10 L8,15 L2,9 L8,3 L8,8 L10.9946916,8 C14.3113318,8 17,10.6930342 17,14 L17,17 L15,17 L15,17 Z" id="Combined-Shape"></path>
                    </g>
                </g>
            </svg>
        </a>
        @foreach( $post->replies as $reply)
            @if ($reply->post_id == $post->id)
            @endif
        @endforeach
        @if (!empty(count($post->replies)))

            <a class="btn btn-primary" href="{{route('replies.create', $post->id)}}">{{ count($post->replies) }}</a>
        @endif
    </div>
    </div>
</div>

resources/views/qchan/_show.blade.php
<x-app>
    <div class="border border-gray-300 rounded-lg">

        <p class="m-0"><strong>
                {{ $post->user->name }} said...
            </strong></p>
        <br>
        <p>{{$post->body}}</p>
    </div>
    @include('qchan.replies._index')
</x-app>

resources/views/qchan/_timeline.blade.php
<div class="border border-gray-300 rounded-lg">
    @forelse($posts as $post)
        @include('qchan._posts')
    @empty
        <p class="p-4">No Posts yet</p>
    @endforelse
        {{ $posts->links() }}
</div>